export interface MenuItem {
  id: string;
  name: string;
  description: string;
  price: number;
  image: string;
  category: string;
  nutritionalInfo?: {
    calories: string;
    protein: string;
    carbs: string;
    fat: string;
    [key: string]: string;
  };
}

export const menuItems: MenuItem[] = [
  {
    id: "hummus-platter",
    name: "Hummus Platter",
    description: "Creamy hummus served with warm pita bread and olive oil",
    price: 8.99,
    image: "/images/food/hummus.jpg",
    category: "Appetizer",
    nutritionalInfo: {
      calories: "280",
      protein: "8g",
      carbs: "32g",
      fat: "14g",
    },
  },
  {
    id: "stuffed-grape-leaves",
    name: "Stuffed Grape Leaves",
    description: "Grape leaves filled with rice, herbs, and pine nuts",
    price: 9.99,
    image: "/images/food/dolma.jpg",
    category: "Appetizer",
    nutritionalInfo: {
      calories: "220",
      protein: "6g",
      carbs: "28g",
      fat: "10g",
    },
  },
  {
    id: "baba-ganoush",
    name: "Baba Ganoush",
    description: "Smoky eggplant dip with tahini and garlic",
    price: 8.99,
    image: "/images/food/baba-ghanoush.jpg",
    category: "Appetizer",
    nutritionalInfo: {
      calories: "250",
      protein: "6g",
      carbs: "18g",
      fat: "16g",
    },
  },
  {
    id: "falafel-platter",
    name: "Falafel Platter",
    description: "Handcrafted falafels served with hummus, pita, and tahini sauce",
    price: 12.99,
    image: "/images/food/falafel-platter.jpg",
    category: "Appetizer",
    nutritionalInfo: {
      calories: "380",
      protein: "15g",
      carbs: "42g",
      fat: "18g",
    },
  },
  {
    id: "spanakopita",
    name: "Spanakopita",
    description: "Crispy phyllo pastry filled with spinach and feta cheese",
    price: 10.99,
    image: "/images/food/spanakopita.jpeg",
    category: "Appetizer",
    nutritionalInfo: {
      calories: "320",
      protein: "12g",
      carbs: "28g",
      fat: "20g",
    },
  },
  {
    id: "stuffed-mushroom",
    name: "Stuffed Mushroom",
    description: "Portobello mushrooms filled with Mediterranean herbs and cheese",
    price: 11.99,
    image: "/images/food/sutuffed-mushroom.jpeg",
    category: "Appetizer",
    nutritionalInfo: {
      calories: "180",
      protein: "8g",
      carbs: "12g",
      fat: "14g",
    },
  },
  {
    id: "grilled-lamb-kebabs",
    name: "Grilled Lamb Kebabs",
    description: "Tender lamb marinated in Mediterranean spices, served with tzatziki sauce",
    price: 24.99,
    image: "/images/food/grilled-lamb-kebabs.jpg",
    category: "Main Course",
    nutritionalInfo: {
      calories: "450",
      protein: "35g",
      carbs: "12g",
      fat: "28g",
    },
  },
  {
    id: "seafood-paella",
    name: "Seafood Paella",
    description: "Authentic Spanish-style paella with shrimp, mussels, and saffron rice",
    price: 28.99,
    image: "/images/food/seafood-paella.jpg",
    category: "Main Course",
    nutritionalInfo: {
      calories: "520",
      protein: "32g",
      carbs: "45g",
      fat: "22g",
    },
  },
  {
    id: "falafel-main",
    name: "Falafel Main Course",
    description: "Generous portion of falafels served with rice, salad, and tahini sauce",
    price: 18.99,
    image: "/images/food/falafel-platter.jpeg",
    category: "Main Course",
    nutritionalInfo: {
      calories: "480",
      protein: "18g",
      carbs: "52g",
      fat: "22g",
    },
  },
  {
    id: "chicken-shawarma",
    name: "Chicken Shawarma",
    description: "Marinated chicken with garlic sauce, pickles, and fresh vegetables",
    price: 16.99,
    image: "/images/food/chicken-shawarma.jpeg",
    category: "Main Course",
    nutritionalInfo: {
      calories: "420",
      protein: "38g",
      carbs: "25g",
      fat: "20g",
    },
  },
  {
    id: "moussaka",
    name: "Moussaka",
    description: "Layers of eggplant, minced meat, and béchamel sauce",
    price: 22.99,
    image: "/images/food/moussaka.jpeg",
    category: "Main Course",
    nutritionalInfo: {
      calories: "480",
      protein: "28g",
      carbs: "32g",
      fat: "30g",
    },
  },
  {
    id: "stuffed-bell-peppers",
    name: "Stuffed Bell Peppers",
    description: "Bell peppers filled with rice, herbs, and Mediterranean spices",
    price: 19.99,
    image: "/images/food/stuffed-bell-peppers.jpeg",
    category: "Main Course",
    nutritionalInfo: {
      calories: "350",
      protein: "12g",
      carbs: "45g",
      fat: "15g",
    },
  },
  {
    id: "grilled-sea-bass",
    name: "Grilled Sea Bass",
    description: "Fresh sea bass with lemon and herbs, served with seasonal vegetables",
    price: 29.99,
    image: "/images/food/grilled-sea-bass.jpeg",
    category: "Main Course",
    nutritionalInfo: {
      calories: "380",
      protein: "42g",
      carbs: "8g",
      fat: "22g",
    },
  },
  {
    id: "vegetable-tagine",
    name: "Vegetable Tagine",
    description: "Slow-cooked vegetables with Moroccan spices and couscous",
    price: 17.99,
    image: "/images/food/vegetable-tagine.jpeg",
    category: "Main Course",
    nutritionalInfo: {
      calories: "320",
      protein: "10g",
      carbs: "48g",
      fat: "12g",
    },
  },
  {
    id: "kunafa",
    name: "Kunafa",
    description: "Sweet cheese pastry soaked in sugar syrup",
    price: 8.99,
    image: "/images/food/kunafa.jpeg",
    category: "Dessert",
    nutritionalInfo: {
      calories: "380",
      protein: "8g",
      carbs: "52g",
      fat: "18g",
    },
  },
  {
    id: "halva",
    name: "Halva",
    description: "Traditional sesame-based dessert with pistachios",
    price: 6.99,
    image: "/images/food/halva.jpeg",
    category: "Dessert",
    nutritionalInfo: {
      calories: "280",
      protein: "6g",
      carbs: "32g",
      fat: "16g",
    },
  },
  {
    id: "orange-cake",
    name: "Orange Cake",
    description: "Moist orange cake with citrus glaze",
    price: 7.99,
    image: "/images/food/orange-cake.jpeg",
    category: "Dessert",
    nutritionalInfo: {
      calories: "320",
      protein: "4g",
      carbs: "45g",
      fat: "14g",
    },
  },
  {
    id: "rice-pudding",
    name: "Rice Pudding",
    description: "Creamy rice pudding with cinnamon and pistachios",
    price: 6.99,
    image: "/images/food/rice-pudding.jpg",
    category: "Dessert",
    nutritionalInfo: {
      calories: "280",
      protein: "6g",
      carbs: "42g",
      fat: "12g",
    },
  },
  {
    id: "turkish-delight",
    name: "Turkish Delight",
    description: "Traditional rose-flavored Turkish delight with powdered sugar",
    price: 7.99,
    image: "/images/food/turkish-delight.jpg",
    category: "Dessert",
    nutritionalInfo: {
      calories: "320",
      protein: "2g",
      carbs: "68g",
      fat: "0g",
    },
  },
  {
    id: "baklava",
    name: "Baklava",
    description: "Layers of flaky phyllo pastry filled with chopped nuts and sweetened with honey syrup",
    price: 8.99,
    image: "/images/food/Baklava.jpg",
    category: "Dessert",
    nutritionalInfo: {
      calories: "380",
      protein: "6g",
      carbs: "45g",
      fat: "22g",
    },
  },
  {
    id: "mint-lemonade",
    name: "Mint Lemonade",
    description: "Fresh mint and lemon with a touch of honey",
    price: 4.99,
    image: "/images/beverages/lemonade.jpeg",
    category: "Beverage",
    nutritionalInfo: {
      calories: "120",
      protein: "0g",
      carbs: "28g",
      fat: "0g",
    },
  },
  {
    id: "turkish-coffee",
    name: "Turkish Coffee",
    description: "Traditional Turkish coffee served with cardamom",
    price: 3.99,
    image: "/images/beverages/turkish-coffee.jpg",
    category: "Beverage",
    nutritionalInfo: {
      calories: "5",
      protein: "0g",
      carbs: "1g",
      fat: "0g",
    },
  },
  {
    id: "rose-water-lemonade",
    name: "Rose Water Lemonade",
    description: "Refreshing lemonade with a hint of rose water",
    price: 5.99,
    image: "/images/beverages/rose-water.jpeg",
    category: "Beverage",
    nutritionalInfo: {
      calories: "140",
      protein: "0g",
      carbs: "32g",
      fat: "0g",
    },
  },
  {
    id: "ayran",
    name: "Ayran",
    description: "Traditional yogurt drink with salt and mint",
    price: 3.99,
    image: "/images/beverages/ayran.jpeg",
    category: "Beverage",
    nutritionalInfo: {
      calories: "80",
      protein: "4g",
      carbs: "6g",
      fat: "4g",
    },
  },
  {
    id: "mint-tea",
    name: "Mint Tea",
    description: "Fresh mint tea served hot",
    price: 2.99,
    image: "/images/beverages/mint-tea.jpg",
    category: "Beverage",
    nutritionalInfo: {
      calories: "2",
      protein: "0g",
      carbs: "0g",
      fat: "0g",
    },
  },
  {
    id: "pomegranate-juice",
    name: "Pomegranate Juice",
    description: "Fresh pomegranate juice with a hint of mint",
    price: 5.99,
    image: "/images/beverages/pomegranate-juice.jpg",
    category: "Beverage",
    nutritionalInfo: {
      calories: "160",
      protein: "2g",
      carbs: "38g",
      fat: "0g",
    },
  },
  {
    id: "jallab",
    name: "Jallab",
    description: "Traditional drink made with dates, grape molasses, and rose water",
    price: 4.99,
    image: "/images/beverages/jallab.jpeg",
    category: "Beverage",
    nutritionalInfo: {
      calories: "180",
      protein: "1g",
      carbs: "42g",
      fat: "0g",
    },
  },
  {
    id: "sahlab",
    name: "Sahlab",
    description: "Warm milk drink with orchid root powder and cinnamon",
    price: 4.99,
    image: "/images/beverages/sahlab.jpeg",
    category: "Beverage",
    nutritionalInfo: {
      calories: "220",
      protein: "8g",
      carbs: "32g",
      fat: "6g",
    },
  },
  {
    id: "orange-blossom-water",
    name: "Orange Blossom Water",
    description: "Refreshing drink with orange blossom essence",
    price: 3.99,
    image: "/images/beverages/orange-blossom-water.jpeg",
    category: "Beverage",
    nutritionalInfo: {
      calories: "40",
      protein: "0g",
      carbs: "8g",
      fat: "0g",
    },
  },
]; 